#!/bin/bash

COMMAND="$@"

if [ -n "$COMMAND" ]
then
	sudo services start
	echo "[*] Executing '$COMMAND'"
	# Use exec to pass signals to $COMMAND
	exec $COMMAND
else
	echo "/!\\ No command provided"
	exit
fi
