#!/bin/bash

start_services() {
	echo "[*] Starting the databases"
	service mysql start
	service redis-server start
	
    RET=1
    while [[ RET -ne 0 ]]; do
        echo "Waiting for MySQL..."
        sleep 2
        mysql -u root -e "status" > /dev/null 2>&1
        RET=$?
    done
}

stop_services() {
	echo "[*] Gracefully stopping the databases"
	service redis-server stop
	service mysql stop
}

case "$1" in
	start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 3
        ;;
esac

exit 0
